### ISSUE TITLE
Suggestion: Disenchant Minimum

### ISSUE THREAD

**Issue by CorvinusRex** [shirsig/aux-addon#104]
I often find that the weighted average is less helpful than knowing what the least amount (lowest disenchant outcome value) I can make disenchanting.  I can figure it out by looking at the distribution and then searching for the lowest value material that would result, but it would be nice to have it shown on the tooltip.

Also the minimum would be much more useful in calculating the Disenchant Profit filter, as it would avoid losses due to RNG and not just the disenchant mats market shifting.

**Comment by Sk1nk** [comment]
I would second that. Knowing the minimal disenchant value of an item could even help in building some new filters for a reliable source of income, since profit could just be higher, but not lower and not lead to a loss.

**Comment by shirsig** [comment]
I see two problems:
- It's not actually minimal anyway because it's based on the historical value of the material which may be wrong.
- The value of the least valuable outcome is usually so small compared to the expectation value that you'll literally never find an auction priced that low (I think usually it would even be lower than the vendor value)

Also, the disenchant value is probably usually not reliable for low level items anyway as usually not all of the outcomes have an active market and for the few high level ones if you disenchant frequently you'll know the values by heart anyway.
