### ISSUE TITLE
Suggestion: History of the cost of adding an item multiple times to AH

### ISSUE THREAD

**Issue by yoyosan** [shirsig/aux-addon#105]
Hello @shirsig !

Thank you for this great addon. It helps me a lot with managing the AH!

Here's is my suggestion. I find myself posting multiple BOE items(and not only these) multiple times to the AH without knowing exactly whether the cost of depositing them will still make me a profit.
It would be great if a history of deposits will be kept for certain items(or all items) and I would be informed, before posting the item again, about the fact that I'm no longer making a profit so that I can vendor it.

What do you think?

Cheers.

**Comment by shirsig** [comment]
Hey. I don't see it, sorry. First of all, it's not clear how it could be implemented at all, given that there's no way to uniquely identify a specific item and thus know how many times it was auctioned. Then also it's not clear what you mean by profit/if that makes sense. You always stand to make a profit when auctioning, no matter how often it's already been auctioned. Of course you shouldn't keep auctioning something that doesn't sell forever or you'll lose more money on deposits than you could sell it for, but you probably should stop long before reaching that point. And once you have reached that point the money you've already lost shouldn't influence the decision to auction (beyond insofar as it indicates the likeliness of the sale) because the money is already lost anyway.
