### ISSUE TITLE
Buyout Not available

### ISSUE THREAD

**Issue by Monteo** [shirsig/aux-addon#113]
![image](https://user-images.githubusercontent.com/24656088/27587699-79f7dab4-5b6f-11e7-9a4b-9a9061bc7d6a.png)

**Comment by Monteo** [comment]
exactly It is impossible to buy a mark of sargeras

**Comment by shirsig** [comment]
This is the tbc version from the dev branch, right? Do you have the newest version? Tried deleting the savedvars in case you updated? I recall fixing a similar bug but don't have an install of tbc right now so I can't test it.

**Comment by Monteo** [comment]
yes this is tbc dev
last update.
Complete installation did not help
And you can not right-click in the search for an item from the inventory

**Comment by shirsig** [comment]
It only happens with this item? Sure you deleted the savedvariables? I think the bug was with the hyperlink format and there might be a wrong one cached in the savedvariables.
The right click was disabled on purpose because hooking UseContainerItem like in vanilla doesn't work and I haven't had time to figure out an alternative solution for the right click shortcuts

**Comment by Monteo** [comment]
Until I came across this item, yes i del all data aux from SavedVariables and clean cache

**Comment by shirsig** [comment]
should be fixed now
