### ISSUE TITLE
The stack size slider in the Post tab changes the Auction Bid (per item) values

### ISSUE THREAD

**Issue by dasmorton** [shirsig/aux-addon#117]
If I adjust the stack size when posting an auction, the auction bid per item values change as well which makes it difficult to set an appropriate bid price. See the images below for an example.

1. Stack size set to 1, the auction bid per item is shown correctly
![image](https://user-images.githubusercontent.com/8152824/28036070-c4e58348-65ae-11e7-9747-eedc5bed6576.png)

2. Stack size set to 9, the same auction is now shown as 1/9 of the original value
![image](https://user-images.githubusercontent.com/8152824/28036150-21a5144a-65af-11e7-95af-88cc574228dc.png)

**Comment by dasmorton** [comment]
It looks like it's dividing the total bid price by the selected stack size, rather than dividing by the stack size of the relevant auction.

**Comment by shirsig** [comment]
The only reason to set a bid price different from the buyout is to appear higher in the default ah, but for that you have to undercut the stack prices because the default AH only sorts by bid-stack price. The bid listing shows you what kind of unit price you have to undercut to be listed in a certain position.
