### ISSUE TITLE
Realtime search not working

### ISSUE THREAD

**Issue by njc07008** [shirsig/aux-addon#135]
Whenever I do a RT search (empty query), nothing or only items I just listed show up. This has been the case for a couple weeks. Prior to this, every 5 days or so a RT query would bug and only a fixed list of items all with the same duration (24h, 8h, 2h) would be displayed, and this would be the only results I got until those auction duration had expired.
I have deleted the saved .lua files associated to aux and re-downloaded multiple times, and I do not have many add-ons. I am on Mac if that helps.

 Is there a user-end fix?

**Comment by shirsig** [comment]
If you're talking about elysium, not sure if the ah is just broken or if it's so large that the size fluctuates so much that it's impossible to reliably calculate the last page. Either way, the time sorting is non-blizzlike so real-time wouldn't work anyway. The only thing you can do is use a filter that only returns one page.

**Comment by njc07008** [comment]
Yeah I am talking about Lightforge (Elysium). Could this be related to them changing servers? It used to work 95% of the time on Elysium. Thank you for the suggestion though (and the add-on as whole), it works.

**Comment by shirsig** [comment]
No. Either it's because they broke the code or because the ah is larger than ever before (800+ pages, I only remember like 600 max from nostalrius) Pretty sure AH sorting was broken most of the time already though, so you would've gotten something, but not the most recent auctions. Perhaps they even changed it on purpose to prevent sniping.
