### ISSUE TITLE
Post shows wrong values for 'per item' bid price

### ISSUE THREAD

**Issue by joelgriffiths** [shirsig/aux-addon#149]
It actually appears to be showing the unit price divided by the quantity.  Digging through the code, I've decided that I simply don't understand lua. In addition to that though, I can change this line in core.lua:

118             local price = record.unit_price * (listing == 'bid' and record.stack_size / stack_size_slider:GetValue() or 1)

to

118             local price = record.unit_price * (listing == 'wtf' and record.stack_size / stack_size_slider:GetValue() or 1)

and I will get the correct auction bid prices on the Post tab. It doesn't help when I click on it though. It still populates my unit starting price with the wrong value.

I'm still looking at it, but my lua sucks.

**Comment by shirsig** [comment]
It's meant to be this way. It shows the pseudo-unit price that you would be undercutting (because actually you're undercutting the stack price, that's the whole point of the bid listing, undercutting stack bid prices so you appear higher up in the sorting of the default blizzard AH which can only sort by stack bid prices)

**Comment by joelgriffiths** [comment]
Yes. That's what it supposed to be doing, but that's not what's happening. For instance. When I try to post an Auction of heavy stone, the Post tab shows the cheapest bid at 23c/unit. When I look at the Blizzard pane. the cheapest bid price is actually 2s87c/unit.

**Comment by shirsig** [comment]
That's because the stack size is different. If you have a larger stack size you need to undercut a lower pseudo unit price to undercut the stack price. That's why it's divided by your selected stack size, not by that auction's stack size.

**Comment by shirsig** [comment]
let's say there's an auction of 1 murloc eye with bid price 10c. You wanna post an auction of 10 murloc eyes. That auction's unit bid price is 10c, but in order to undercut its bid stack price with your stack size of 10 you need to have a unit price of less than 1c or in other words you need to undercut the "pseudo unit price" of 1c which is what aux is showing.

**Comment by joelgriffiths** [comment]
I think I finally see the logic problem here. 

It looks like it's taking the AH price, dividing it by MY stack size, not the AH stack size for the same item.

In my case, I have 12 [Heavy Stone]

The cheapest AH bid price is currently a 1 item stack (not really a stack) for 2.87s

On my Post page, it grabs that 1 item stack and divides it by my 12 item quantity so it wants to set my unit bid price to 23c when it should be setting it to 2.86s - one copper less than the price of the cheapest unit price on the AH.

**Comment by shirsig** [comment]
Yes, that's how it's supposed to be!

**Comment by joelgriffiths** [comment]
Why doesn't the slider change the Auction bid (per item price), but not the Auction buyout (per item price)?

**Comment by shirsig** [comment]
Because with the buyout you wanna undercut the unit price and with the bid you wanna undercut the stack price.

**Comment by joelgriffiths** [comment]
I love your addon man. I really appreciate your responses though. I would much rather be playing the game that writing code, so I know it takes a lot to do what you do.

**Comment by shirsig** [comment]
Thanks. Note that I'm aware this feature can be rather unintuitive (and it is disabled by default).
It's a very specialized feature meant more for increasing the likelihood of people buying your buyouts than having much to do with bidding.

**Comment by joelgriffiths** [comment]
Since it was posting my stuff orders of magnitudes cheaper than the next lowest cost item on the AH, I forked the code and applied a couple changes that made it behave more along the lines of the way I wanted it to behave. I need to work on the sorting though.

**Comment by shirsig** [comment]
Well it doesn't automatically price anything. The prices in the bid listing are to be seen more as a warning than as a recommendation. The listing is sorted by stack bid price, so the same order as the auctions will appear in the blizzard auction house when using its limited price sorting. The position of the item in the listing you undercut corresponds to the position your auction will have in the AH, and the pseudo unit price tells you how low a unit bid price you need to risk in order to "buy that position".

**Comment by joelgriffiths** [comment]
It doesn't really give you the price in the AH. It gives the cost of the cheapest item in the AH - then it divides it by the number of units I want to sell. The numbers don't really have anything to do with one another.

If there is 1 Gold Bar in the AH for 90s/1G, and I want to sell one of mine, it tells me the cheapest undercut price on the AH is 89s/99s per bar. That makes sense to me.

Now, if I want to sell 10 of mine, it tells me the cheapest undercut price on the AH is 8s/99 per bar. That's a huge discount.

If I want to sell 20 Gold Bars, it gets better. Aux tells me the cheapest undercut price is 5s/99s per bar.

Now that I changed a couple lines, it will use the price at 89s/99s per bar, no matter how big my stacks are. 

I just have to believe that I'm completely off base here and am missing the whole point. It wouldn't be the first time; I argue with devs for a living too.

**Comment by shirsig** [comment]
You're missing the point. Like I said, the bid listing is not meant for bidding. (though even the "real" bid price of auctions should never be used as a price indicator because it may start way below the market value and the poster can always cancel so there's no risk in posting "fake" low bids)

You should use the buyout listing as an indicator for the value (besides aux' historical value, which is also based only on buyout values) even for your bid price choices.

The only purpose of the bid listing in aux is to help you undercut _stack bid prices_ which helps you trick people into buying your buyouts even if they're not the cheapest because they will appear at the top of the price sorted default blizzard AH.
