### ISSUE TITLE
no Bid tab when posting auctions

### ISSUE THREAD

**Issue by yarvaxea** [shirsig/aux-addon#154]
I can only see and set prices for buyouts when posting auctions. I used to be able to set a bid price and a buyout price, now I can't seem to do anything with the bid price at all.

**Comment by shirsig** [comment]
You can edit the prices manually. Theres a "bid listing" you can activate in the settings but its not the same and meant only for undercutting the stack bid prices to appear higher up in the blizzard ah. I dont think a bid listing is particularly interesting as it doesnt indicate the calue as well as buyout prices and undercutting the unit price for bids seens kinda pointless because if you do get a bid ull no longer be lower and if you expect only one bid you might as well set it as buyout
