### ISSUE TITLE
Multiple Item Class Search?

### ISSUE THREAD

**Issue by fgsfdss** [shirsig/aux-addon#165]
Maybe I'm doing something wrong, but I'm having issues in- and excluding multiple item classes in a query.

For example, to scan the entire auction house except for Quivers and Projectile, I would do something like:
`not/or/quiver/projectile`
But this doesn't seem to work. (It seems the "not" parameter only goes for item names?)

So I'd try to include all categories except for those:
`or8/weapon/armor/container/consumable/trade goods/recipe/reagent/miscellaneous`
But this doesn't work either.

Is it even possible? The filter builder doesn't help much either, as it resets my query when choosing a different item class.

**Comment by shirsig** [comment]
There is no post filter for categories. What you're doing here is tooltip filtering. But even if there were it wouldn't do what you're expecting because post filters cannot influence what's scanned, only what's displayed. You can do multiple blizzard queries, but for those you cannot use aux' operators like "not".
Blizard queries are separated by semicolons. You can do this: weapon;armor;container;consumable;trade goods;recipe;reagent;miscellaneous. However, if you wanna add post filters to this you have to add them to every query separately.

**Comment by fgsfdss** [comment]
Very helpful, thank you. This is even better as I can specify profit values and percentages per category.
