### ISSUE TITLE
Some crafting costs inaccurate.

### ISSUE THREAD

**Issue by Malevola** [shirsig/aux-addon#187]
I've noticed that occasionally the crafting cost of an item seems wildly inaccurate.

Alchemy: Elixir of Water Breathing
    Stranglekelp x 1 (Aux Value in tooltip 7s 90c)
    Blackmouth Oil x 2 (Aux Value in tooltip 1g 50s)
    Empty Vial x 1 (Aux Value in tooltip 2s 49c, although this is a vended item which is much cheaper)

Reagent cost in the crafting window: 4s 83c.

I couldn't even figure out how the calculation was performed to get that number.

**Comment by shirsig** [comment]
If I remember correctly the vendor sell price is used sometimes. I think it should only be if the vendors sell unlimited quantity but in some cases the item price databases that I created aux' from were incorrect about that, especially for a lot of herbs. (Think because of some special vendors that appeared only during some event). Maybe downloading a new version of the aux item prices might fix it or else you could manually fix it in the savedvariables file (I assume in this case stranglekelp is incorrectly marked as unlimited quantity)

**Comment by shirsig** [comment]
There should be a table called aux_merchant_buy somewhere in the account wide aux savedvariable file.

This table has entries like this:
```[3820] = "400#0",``` (think this is the stranglekelp one) where on the left is the itemid and on the right price#limited (1 means limited, 0 means unlimited) so if u change the 0 to 1 it should work.

Feel free to make a pull request to the aux merxhant price repo if u fix something (also increment the version at the top of the file)
