### ISSUE TITLE
discoverability of per item view or other UI/doc suggestions

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#188]
I started to write the following 

"Aux is a fantastic addon but something puzzles me:

Why are the prices of stackable items per stack - how is that useful vs per item - or is there a way to toggle it ...'

And I tried clicking, shift clicking and eventually found that right click shifts the view ! woot !

Is there a way to make tooltips for aux ? or a small guide ? such as those feature are easier to discover?

Also can aux have a "settings" tab to change its behavior (like how it undercuts, or the default view etc...)

Thanks again for a fantastic addon - do you plan on making it work for classic on release date?

**Comment by shirsig** [comment]
Hey. I'm glad you like the addon. The reason the default listing shows stack prices (though you can toggle it as you found out) is because that's what you're actually paying when you're buying an auction. Showing unit prices can be a bit dangerous for example if you're buying ammo which comes in stacks of 200 (i.e., you might accidentally pay a lot more than you think). Also, the percentage already gives me pretty much the same information I would get from the unit price so I personally prefer to have it show stack prices.

My addons tend to have little or no settings (guess you could call that "opinionated" design, or "lazy" if you're more cynical xD) Anyway, I like simplicity and I don't have much spare time these days to work on these things so documentation is secondary. The readme file of this repo is the only documentation there is but there isn't that much complexity to the user interface anyway apart from the filters (for which the filter builder tab serves as a bit of a tutorial) and all the settings you can see if you type **/aux**

Whether I will make it work for the official classic wow depends on what kind of scripting interface it will have. If it is close enough to vanilla that it will require little modification then I will make it work. If it is closer to the retail interface then there will be no point as the retail addon authors will probably make theirs work for that.
