### ISSUE TITLE
suggestion: search in last scan/in memory db

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#190]
I would love to scan only once and then perform a number of searches (scanning is very slow if I want to do both a vendor scan and a profit one, it'd be nice to be to run a main/more time sensitive one as the main one, then remember the last data set and have that one searchable )

**Comment by shirsig** [comment]
I've considered something like this many times but I think the added complexity of having those two types of searches is not worth it for various reasons. Scanning in vanilla is so slow that after a full scan the data set is not fresh enough (most good deals will already be gone) and also with the amount of auctions on active vanilla servers there is too much data to cache it all and search it without significant lags, which is also why there is a limit of 1000 or something (don't recall the exact number) per result table because beyond that things like sorting would not be possible anymore without significant lags. Of course I could implement sorting or filtering in a way that would do it in increments but that would add extreme complexity for very little gain.

I know vanilla auctioneer does something like this but I've personally never found it all that useful. Unlike aux it doesn't keep track of all the individual auctions but considers auctions of the same price, item and stack size as equal and only counts them once, and unlike aux it does not keep a reference to the location of auctions so it needs to do a full scan again to find a specific item.
