### ISSUE TITLE
Scan only shows 24h auctions

### ISSUE THREAD

**Issue by ClockWise89** [shirsig/aux-addon#207]
I'm using the filter builder in aux to search auctions, but if I use left/30m or left/2h I get no auctions at all, but if I change to left/24h I get auctions with 24h left.

Even searching using only trade goods/common shows me only 24h left on auctions, until I look at a specific item, there I can see all the auctions for 30m, 2h, 8h etc. But I can't filter at all on any other time left than 24h.

`trade goods/common/left/8h` - Shows me 0 auctions
`trade goods/common/left/24h` - Shows me ton of auctions. If I right click to see all auctions of a specific item I see auctions with all kinds of time left, but the overall search only shows 24h.

**Comment by shirsig** [comment]
I set the auction house sorting for aux scans to duration starting with longest. I think you just didn't let the queries run through? The shorter durations would come at the end and the first pages will only contain 24h auctions.

**Comment by ClockWise89** [comment]
Ah, I see. This wasn't case when I used Aux on the pirate servers, so I was basically just too impatient to wait for the search to finish since it takes a while. It seems to work, even if i'd rather have it the other way around i.e. lowest time left first.

**Comment by shirsig** [comment]
I changed it to longest first because it makes the real time scan more efficient (don't need a useless query just to determine the last page but can just scan always the first page.

Actually sniping is kind of broken though because the vanilla blizzlike ah sorting was by time the auctions were put on, not by duration left, and this is not available in classic/retail. Sniping will thus only get the newest auctions with 24h, not the newest auctions of any duration setting. (unless you make blizzard query that only returns one page to begin with of course, then it works fine) Anyway, this is the closest we can get and also what TSM does afaik.

The sorting for non real time scans could theoretically anything of course, I just made it the same for consistency and because it simplifies the code. Why do you think having the soon expiring ones first would be better? (or any other for that matter. The classic api actually offers sorting across pages for quality, level, status, duration, bid, name, and buyout, and the reverse order for each)

**Comment by ClockWise89** [comment]
Ah I see, well it doesn't really matter for 2h or 8h, but 30min could matter. Since they can end any second and it takes like 5-10min to search them all when they are last.

But it ain't no biggie, I just thought it didn't work at all so now I'm happy when it does. Love this addon btw.

**Comment by shirsig** [comment]
True, but on the other hand the best deals are usually bought out quickly and never reach a low duration and if you start with the low ones they might already be gone when your reach the high durations.

Anyway, I might consider even making it a setting but currently more important issues have priority.

**Comment by ClockWise89** [comment]
Yeah, unless its a low bid on the 30m. Buy out is almost always gone, just like you said.

**Comment by robmonte** [comment]
I agree that 30m listings are important as the bid may be low while the buyout is still a typical price, meaning the listing wasn't sniped by someone. This leaves the possibility of missing low-bid items that are expiring shortly.
