### ISSUE TITLE
Bid price in post screen not working as expected

### ISSUE THREAD

**Issue by robmonte** [shirsig/aux-addon#230]
Maybe I'm not understanding how the bid price when posting items works if it has changed, but this isn't how it worked on Nost/LH so I'm unsure.

The auction bid prices are doing something strange when posting an item. For some reason, the bid price seems to be being divided by the stack size you select. The unit bid starting price shouldn't be rely on stack size at all and should simply be a static list based on listed auctions.

**Comment by shirsig** [comment]
This is working as intended. The bid listing is intended to undercut the **stack** bid price as it appears in the default AH. Since a lot of people found it confusing I changed it slightly in the newest version. Now it shows the stack prices in the listing (otherwise it's exactly the same) though I think dividing it by the selected stack is a bit more useful.

**Comment by robmonte** [comment]
I see. I understand the idea behind this but doubt that this solution is the best. This makes it very easy to list stacks of items WAY below the intended bid price. And unless I'm missing something (I might be honestly) there's no easy way figure out which bid-price-per-item I would actually like to use instead without referring back to the bid price when I set a stack size of 1 and then have to manually type that into the bid price box - for every item i list.

The current example I'm looking at is Greater Healing Potions. My server AH has them listed as such currently, in order:

| Item | Bid | Buyout |
| --- | --- | --- |
|1x Greater Healing Potion | 96c bid | 3s81c buyout |
| 3x Greater Healing Potion | 12s15c bid | 13s50c buyout |
| 5x Greater Healing Potion | 20s bid | 25s buyout |
| 5x Greater Healing Potion | 20s bid | 25s buyout |

etc...

So because one guy threw a single potion up for 96c bid, Aux wants to list my **_entire_** stack of 5 potions I'm listing at a total bid price of 95c. Not 95c per item, 95c in total. (19c per potion for the stack). This is definitely not the desired behavior in this case, or at least it _shouldn't_ be. It should be offering 95c per item instead. Nevermind the fact that that price is FAR less than vendor price too.

At the very least, we should be able to toggle between these two bid-price modes. It's weird people were confused by the previous method, but even if so, I find it hard to believe this way makes "more sense" and especially doubt they'd want to be listing stacks this low.

**Comment by shirsig** [comment]
The idea is to undercut the **stack** price because the default AH can only sort by stack bid price. Undercutting the unit bid price seems kind of pointless as it will go up anyway if someone bids and it doesn't actually help you be high up in the blizzard AH.

What should help you prevent setting the bid way below the value is the historical price percentage column.

Note that you don't have to make the unit bid price low, you can also lower the stack size instead to get higher up in the listing.
