### ISSUE TITLE
Stack size slider broken

### ISSUE THREAD

**Issue by Eric-Johnston** [shirsig/aux-addon#235]
Splitting stack size is broken, for some reason when I try to change stack size at all it says "Couldn't split those items". Not sure why the slider is trying to split the items before I post an auction.

**Comment by Eric-Johnston** [comment]
Edit - Also if I manually split the items into single it doesn't allow me to post multiple single auctions in one click like the 1.12 version allows

**Comment by shirsig** [comment]
Well, it has to happen either before or after you click post. The blizzard API doesn't stack them for you. The advantage to doing it before clicking post is that you will only have to click once, because otherwise you would have to click again for the posting because the API requires a hardware event.

The classic API doesn't allow fully automated posting.
