### ISSUE TITLE
Greater Eternal Essence under hidden items

### ISSUE THREAD

**Issue by fgsfdss** [shirsig/aux-addon#239]
Surely it should not be under hidden items. Is it possible to make the list modifiable?

**Comment by shirsig** [comment]
There's a checkbox in the top right corner when you've selected an item in post.

**Comment by fgsfdss** [comment]
I knew I forgot something. Thought I did this on private servers in the past. My bad.

**Comment by fgsfdss** [comment]
Actually, at first I thought I did this by mistake, but it seems to get hidden again each time I update aux. It only happens for Greater Eternal Essence. Any particular reason for this?

**Comment by shirsig** [comment]
I can't reproduce it. I used a greater magic essence because I didn't wanna buy one of these but I don't see what could be different. Could be a savedvariable issue so you could try **/aux clear post /aux clear item cache /run ReloadUI()**
Or if that doesn't fix it just try deleting all of aux' savedvariables.

**Comment by fgsfdss** [comment]
Just managed to replicate with a Greater Magic Essence also. Not sure if it's related to updating the addon after all since I do this fairly regularly to hceck prices on both greater and lesser:

1. open post tab to scan inventory
2. turn greater essence into lesser
3. click on greater essence in the item list in aux

The greater essence will disappear from the list and be put in the hidden items list.

4. turn the lessers into a greater again, tick "show hidden items"

This does not occur the other way around;, attempting to select the lesser essence in the item list in aux after turning them into a greater simply does nothing.

**Comment by shirsig** [comment]
Oh, this is technically working as intended. When parsing the inventory aux uses certain criteria to exclude items that are not auctionable. The most reliable way to do this would be to try to put each item into the auction slot but at least in 1.12 this was not performant enough so it had to be done using workarounds like tooltip checks which aren't always catching all unauctionable items. Because of this I made it so that when you select an item and aux fails to add it to the auction slot it is hidden to cover for those cases that are missed by the initial filtering. I didn't distinguish between items which aren't in the inventory anymore and ones that are there but can't be placed in the slot because it makes the code simpler and I figured it would be very unlikely to happen and even if it did happen you could still easily manually unhide it.

Anyway, optimizing the inventory listing is one of the last things that remain to complete the port to classic but I consider it low priority.

**Comment by fgsfdss** [comment]
I tested with the Magic Essences of which I had only bought one to test this, so I only had one greater / three lesser at any given time. The lesser remained in the list, but clicking did not open the right half of the post tab, nor did it get removed from the list. Pretty strange inconsistency. When reopening the lessers are off the list, but not put under hidden items (when again splitting the greater into lesser once more they do show up in the list unlike the greater).

At this point it's more of an interesting behaviour report than an issue though, it's quite the minor thing as you said as well.
