### ISSUE TITLE
question about search filters

### ISSUE THREAD

**Issue by desecfutz** [shirsig/aux-addon#253]
I'd like to create a filter that shows me only [Thorium Bar] and [Thorium Ore]. The closest I got was to search for "thorium/trade goods", which also lists engineering items.

There is an "and" function, but it doesn't seem to do anything... ideal would be to search for "thorium bar/exact and thorium ore/exact" and nothing else. Is this possible? 

"trade goods/item/thorium ore/item/thorium bar" starts to search 100s of pages and is very slow... I'm not patient enough to wait for that :(

Thanks in advance!!

**Comment by shirsig** [comment]
Either **thorium bar/exact;thorium ore/exact** is the "naive" solution. This works for all items and it just scans for thorium bar first, then for thorium ore, then adds all the results together. In some cases it can be more efficient to use a common blizzard filter and filter out other items afterwards though. In this case it works to use a blizzard name filter because they have a similar name so you can do this: **thorium/trade goods/or/item/thorium bar/item/thorium ore** but in the end you don't save much. on my server both were 3 pages to scan.
