### ISSUE TITLE
Not possible to post auctions, invalid capture index error

### ISSUE THREAD

**Issue by Larnak1** [shirsig/Aux-Addon#26]
Hello!

I am not able to post any auctions into the auction house using this addon. The "Post" page just does not show me any items and is empty. Everytime i click on the "post" tab, i get the following error:

Invalid capture index
Interface\AddOns\Aux-Addon\info.lua
Line 357
Error number 3

Any suggestions (or fixes) to solve this would be very appreciated :)

Thank you
Larnak

**Comment by shirsig** [comment]
I think whenever someone had this issue it was something with their client missing certain localized strings and could be fixed by redownloading a correct 1.12 client from a trusted source.

To verify if this is the issue you can do /run Aux.log(DURABILITY_TEMPLATE)
If it gives you an error then it's a problem with your client. Otherwise the output would help me figure out what else might be wrong (maybe if you're using a non english client)

**Comment by Larnak1** [comment]
Hello!

thank you for the fast response. I use the German client, so this might indeed be the reason. Do you know which localization is causing this problem?

When I enter the command, I get:
[aux] Haltbarkeit %1$d/ %2$d
"Haltbarkeit" is german for Durability

Thank you!
Larnak

**Comment by shirsig** [comment]
It seems the german client is using a different syntax there for the templates. The "1$" and "2$". Those can be used for reversing the arguments passed to the template, which makes sense for some languages/templates. Here it does not make sense however because the order isn't changed anyway and none of the other locales seem to be using it but oh well, I've made a change that should hopefully fix it.

**Comment by Larnak1** [comment]
I just tested it, seems to fix the problem! :) I can now set up auctions
Thank you very much
