### ISSUE TITLE
Suggestion: alt modifier for unfavorite

### ISSUE THREAD

**Issue by fgsfdss** [shirsig/aux-addon#262]
Maybe I'm just clumsy, but I have unfavourited a few lengthy queries with a full log of recent searches already - meaning I had to rewrite them, assuming I remembered them correctly in the first place - with a simple missclick. The alt-modifier would make it safer, to have an extra confirmation so to speak.

**Comment by shirsig** [comment]
I prefer it this way as it's more consistent (also, alt click is used for toggling the alert).
I think the main reason to make this mistake is being used to right click to open the menu that was there before, but after getting used to the change I don't think it will be an issue. After all you can always easily get it back unless you made like 50 (or whatever the recent search limit is) other unique searches since last using it.
