### ISSUE TITLE
Sharing data between characters/accounts.

### ISSUE THREAD

**Issue by mateszbukaty** [shirsig/aux-addon#29]
Hello,
First and foremost - awesome addon. :)
I'm posting here since you asked to move from Nostalrius forum. I'm fairly new to Github so please excuse me if I posted it in a wrong section but I couldn't find anything else that resembled a forum.

**Questions:**
1. Is it possible to share market data between characters on the same account? Does it happen automatically? 
2. Is it possible to share market data between 2 different accounts? I use characters from account A for bank/ah and characters from account B for playing. I would like to scan ah with account A and use that data on both accounts A & B. Is it possible to automate the data sharing process?

**Issue/thoughts:**
Are you sure that the "today's value" estimation is done correctly? Take a look at this screenshot for example: [http://i.imgur.com/cK0nnxj.png](http://i.imgur.com/cK0nnxj.png). It presents real market data from today from Kronos 2 server. It estimated daily value of wool cloth at 0,72s based on the fact that someone was selling 1 stack of 7 wool cloth at the price of 0,61s each (4,27s total). So the daily value is the lowest found price of even one piece of some good + roughly 15%. From what I understand the historical value is based on the last 11 daily values.

**That implies 2 things:**
1) In the given example all the rest of wool cloth seems overprices - both compared to the daily value and historical value, while in reality (I observe this particular market several times each day) 2,5s-3,5s a piece is the most common price. That observation can probably be applied to lots of other popular/high-in-demand goods.
2) It seems to be extremely easy to manipulate the daily value and therefore the historical value of Aux. One could just simply be posting 1 piece of some fairly cheap but high-in-demand good on the market a few times a day for a very lowered price. All the Aux users who would scan it before it was bought (and those stacks of one aren't being bought immediately) would be manipulated into "thinking" that the true value of that good is much lower and all the other prices are inflated. This kind of manipulation, under the assumption that everyone would use Aux and trust it's data, could in a long term cause the average price of that good to artificially drop.

Correct me if I'm wrong.

Cheers,
Matt

**Comment by shirsig** [comment]
Sharing between characters of the same account happens automatically. Between different accounts addons have no way of communicating anything. It could be automated but not with a wow addon. Basically you just have to copy paste the relevant parts of the savedvariables file (by hand or with a python script or whatever) at the right time.

The historical value is calculated using a (slightly time weighted) median over the last 11 daily values. The point of the median (as opposed to for example an arithmetic mean) is that it is able to completely ignore up to 5 low and high outliers.

The daily value is easy to manipulate (only downwards) even for active markets but you have to do this consistently over a few days to affect the historical value. There's no way to prevent manipulation in general as anyone with enough budget can always completely take over a market. The simplicity of the daily value is for performance reasons (only need storage space linear in the number of items rather than linear in the number of auctions scanned). I don't think downwards manipulation is enough of an issue to change that.

**Comment by mateszbukaty** [comment]
Thanks for the answers!

**Comment by Schaka** [comment]
Couldn't you just create a symbolic link between your WTF folder(s) to make sure your accounts share the same SavedVariables?

**Comment by shirsig** [comment]
The problem is the time when the files are saved. You have to do the copying while you're logged out on the target account or it will be overwritten.
