### ISSUE TITLE
bid post bug fix

### ISSUE THREAD

**Issue by spaecast** [shirsig/aux-addon#313]
There's a bug in the bid posting.
I'm not part of the project but here is the fix:

tabs\post\core.lua:

			-- BID_FIX local price = record.unit_price * (listing == 'bid' and record.stack_size or 1)
			local price = record.unit_price

				-- BID_FIX a.record.unit_price * (listing == 'bid' and a.record.stack_size or 1),
				-- BID_FIX b.record.unit_price * (listing == 'bid' and b.record.stack_size or 1),
				a.record.unit_price,
				b.record.unit_price,

        -- BID_FIX return stack_price / stack_size
        return stack_price

**Comment by shirsig** [comment]
It's not a bug. The bid listing was requested a long time ago by someone for a very specific purpose, to undercut stack prices so that the auction appears high up in the default ah which can only sort by stack bid price.
For all the people who want a unit price version of that listing I've added that option in the tbc beta version of aux: **/aux post bid unit** (**/aux post bid stack** for the old one)
