### ISSUE TITLE
Can't search for elemental earth in SOM

### ISSUE THREAD

**Issue by lvangh** [shirsig/aux-addon#338]
[Elemental earth]/exact returns nothing, but elemental earth without exact returns it. I imagine there are other items like this but haven't come across any yet. 

I wonder if it has something to do with the item id?

**Comment by knasen88** [comment]
all elemental x, essence of x doesnt work

**Comment by GregoryGH** [comment]
same thing with stonescale oil/eel

**Comment by Deamp** [comment]
I had the same issue and fixed it by running

/aux clear item cache
/aux clear post
/aux post bid unit

one of the above fixed it

I had multiple issues because I moved my tbc savevariables over to SOM and people suggested the "/aux post bid unit" command to fix some issues. Before I checked if that command fixed the issues I already ran all 3 above.

**Comment by GregoryGH** [comment]
yea, it helps

**Comment by shirsig** [comment]
I can't reproduce it. Could be because some item data change with the expansion and yes **/aux clear item cache** will help for that. @Deamp if you quit the game without a regular logout (or having done /run ReloadUI() before) then you lose all changes in the addon savedvariables, probably that's why you had to do it again.
