### ISSUE TITLE
Internal auction error.

### ISSUE THREAD

**Issue by tylerhach** [shirsig/aux-addon#345]
Not sure if it's one of my other addons acting up or it's Aux, but i have a lot of issues posting and buying auctions on wotlk prepatch. I keep getting "internal auction error." as the message, and then my auction doesnt post. And when buying auctions, it usually takes 5+ clicks to purchase something for buy out.

**Comment by xyzek** [comment]
experiencing the same issue

**Comment by KevinTyrrell** [comment]
I'm sure @shirsig is already aware of this but WOTLK prepatch seems to have added some sort of throttling system for auction posting and buying. Searching seems unaffected. My guess is the timing and delay on enabling the post/buy button is what will be needed but it's hard to say. Every auction addon is also dealing with these same issues. TSM is unable to bulk post with scroll wheel like before and Auctionator now goes at a snails pace.

Here's an example of Auctionator in the current patch in terms of delay on posting: https://streamable.com/tzzbza

**Comment by shirsig** [comment]
Yes, I noticed this, but I think it's more likely a bug than an intended throttling system. What I observed so far is:
- It only happens on high pop factions.
- It affects api calls made from addon code more than those made from the blizzard auction ui, even if the parameters are the same
- Post and buy after search always fails, even when waiting quite long in between

**Comment by marcelflymark** [comment]
The internal auction error disables the addon.
Reloading the UI resolves the erroneous state (but then
you lose the chat window contents).

**Comment by shirsig** [comment]
I've added a timeout to reenable the button after 5 seconds.

**Comment by mtoedtem** [comment]
I've downloaded the most recent version and it seems to have solve the issue for the first couple posts but after about 5-8 posts it will again throw "Internal Auction Error".

**Comment by viliger2** [comment]
I don't think anything can be done for buying, because most of the time buying error shows up because someone already bought what you wanted to buy and since AH is now throttled, addon cannot update in a reasonable amount of time to see if the listing is still available.
However, posting is another thing, it is pretty clear that posting follows the same throttling as buying\searching, as in, if you try to post multiple items in a row you will get throttles and it will result in an error. For posting a stack I found posting after "Scan" button becomes available again will consistently post an item without issues, I am suggesting implementing the same timeout for "Post" button, that's what Auctionator does. Don't know if much can be done for posting multiple items.

**Comment by shirsig** [comment]
"I am suggesting implementing the same timeout for "Post" button, that's what Auctionator does."
Thanks for the hint. I've implemented that now.

**Comment by mtoedtem** [comment]
@shirsig changes work great. Addons is running super smooth this morning on Bene.
