### ISSUE TITLE
Scan doesn't continue sometimes

### ISSUE THREAD

**Issue by xC0DEB10C** [shirsig/aux-addon#37]
I haven't tested the parameters of this issue much, but I've noticed that the scan will stop or more like hang and not continue sometimes after reaching page 6-8. The issue doesn't seem to happen when disabling the owner ignore. Also I don't notice any scan speed difference when ignoring owners, so there might be an issue somewhere there.

**Comment by shirsig** [comment]
There's definitely a difference though it's not very noticable at the moment on kronos because there's not much lag. On Nost pvp sometimes you'd have to wait an extra 30+ seconds per page for the owners.
Still, if you don't ignore owners you'll find that the results don't appear instantly when you make a query (without being on the 4 second query cooldown imposed by the API).

Does the hanging happen often? I've noticed it too sometimes but not at specific pages. The problem is I guess that the server doesn't respond. I don't have a timeout because this has never been an issue. Maybe a recent change on kronos that makes this happen. I will add a timeout when I have time but it's not that simple to change  that part of the code.

**Comment by xC0DEB10C** [comment]
Ok it doesn't seem to have anything to do with if you ignore the owners or not.
It just stopped at: "Scanning 2 / 2 (Page 24 / 36)" and won't continue. I was searing "weapon;armor"

**Comment by shirsig** [comment]
Added a timeout now. Can you try if it still stops?

**Comment by xC0DEB10C** [comment]
Awe sweet, it doesn't happen anymore - perfect!

**Comment by shirsig** [comment]
Great :)
