### ISSUE TITLE
List generics when posting auctions

### ISSUE THREAD

**Issue by Silun** [shirsig/aux-addon#372]
When I search for a green X of the Y in the Search tab, it will default to the generic X and list all the Ys it has. The same does not happen in the Post tab, it will only list the exact X of the Y item.

It would be a great improvement if the behaviour in the Post tab could be the same as in the Search tab. At least since Cata prepatch, where transmogs dictate price for green items, no question about it. Currently, I have to check every green item in the search to make sure I don't post an expensive transmog item for cheap just because the Post tab doesn't show me the necessary information.

It could be a toggle in the settings or something, but I feel it is an essential and necessary feature from this point forward.

**Example:**

- I want to sell [Murkblood Gloves of Spirit]. 
- I go to the Post tab, alt-click the item, and see zero auctions. I might post for 5g since the item seems to be essentially worthless. 
- When I go to the Search tab and alt-click there, it checks for all generic [Murkblood Gloves] and I can instantly see that the item is worth hundreds of gold simply because of its transmog.

This fallback to the generic [Murkblood Gloves] is very important and should be available in the Post tab, as well!

**Comment by shirsig** [comment]
Aux is fundamentally designed for vanilla 1.12 and even with classic era some design choices are no longer optimal. The text search api in vanilla did not support suffixes, and aux has the dedicated tooltip filter in order to filter to filter for specific stats (as even the same suffix can still have different stats, and the exact stats are very important because of twink items). I think now in era/cata the api may support text search with suffix, but autocompleting those is problematic because unlike the base item names they cannot be fetched from the API, so that would require a redesign of the whole autocomplete system. Note that in any case while the search tab does not let you search for specific suffixes it will still distinguish them in the search results and not mix them together in groups, like the post tab.

The reason the post tab distinguishes the suffixes (not just by name but by exact suffix id) is again because of the importance of twink items in vanilla.

Now, I agree with your complaints and I would accept a pull request for such a change, but since I myself have no interest in Cata whatsoever I will not be working on any features for it, sorry.

**Comment by Silun** [comment]
Thank you for your response! Reading your post, I get a bit confused. These passages here:

> but autocompleting those is problematic

and

> that would require a redesign of the whole autocomplete system

really sound like we are misunderstanding each other. In no way am I asking about changes to the autocomplete system or anything that relates to the search tab. I am not complaining about anything, either.

You explained that you have coded features into aux to make it possible to distinguish suffixes in the post tab. I am asking for a way to _disable_ this distinguishing behaviour, so that the post tab mixes all suffixes in with each other. The result would be that when someone posts [Cunning Helmet of the Whale], they see all [Cunning Helmet of the Monkey], [Cunning Helmet of the Bear] etc. right in the post tab.

From your post it sounds more like simply disabling the logic that does the extra steps, rather than coding a whole new feature. Again, I am not complaining, I am just trying to make sure we understand each other.

**Comment by shirsig** [comment]
I was just explaining the historical reasons why the search tab works differently with regard to suffixes (if it weren't for the problem with the autocompletion I would've enabled it for searching as well), and that it still also distinguishes them to some extent. It is also distinguished for other things like the historical price calculation. Removing that only from the post tab would be inconsistent.

To my mind feature is something that changes the functionality and requires code changes and testing. Whether it primarily requires adding or deleting code has no bearing on it. And most likely this would require changes in multiple places in order not to break anything.
