### ISSUE TITLE
[REQUEST] Beancounter alike feature

### ISSUE THREAD

**Issue by cnolimes** [shirsig/aux-addon#44]
Greetings Simon,

It would be awesome if you implement some feature that keeps track of what and what amount you've sold/bought for what price. If you are not sure what Beancounter is like, it is an addon from the Auctioneer pack.

Regards.

KS

**Comment by shirsig** [comment]
Hey. I know about beancounter/tsm accounting. The thing is, even though it comes bundled with auctioneer/tsm, because of the way the API works, this isn't really an auction house addon but more of a mailbox/tradeframe addon and I can't think of a good reason to build it into aux. The autumn semester's just started so I won't have time for it in the near future but I guess I could make an addon like that at some point. What's wrong with beancounter though, can't you use that?

**Comment by cnolimes** [comment]
Well, beancounter often fails to register the mails I'm opening. Using Postal btw

**Comment by shirsig** [comment]
I don't think it's a good fit for aux as like I said it's more of a mailbox addon and also there's no reason to show it only at the auction house like aux.

In case someone else wants to make something like this here's what I think is the only way to reliably retrieve this information in combination with an auto opening addon:

```
local index
CreateFrame('Frame', InboxFrame):SetScript('OnUpdate', function()
	if index then
		if GetInboxInvoiceInfo(index) then
			local invoiceType, itemName, playerName, bid, buyout, deposit, consignment = GetInboxInvoiceInfo(index)
			local _, _, count = GetInboxItem(index)
			-- do stuff
			index = nil
		end
	else	
		for i = 1, GetInboxNumItems() do
			local _, _, _, _, _, _, _, _, read = GetInboxHeaderInfo(i)
			if not read then
				GetInboxText(i)
				index = i
				return
			end
		end
	end
end)
```
