### ISSUE TITLE
attempt to perform perform arithmetic on field time

### ISSUE THREAD

**Issue by FlorianKromer** [shirsig/aux-addon#49]
Hi,
First, let me thank you for your very usefull addon.

Since I updated this addon with the last version I got this exception. It comes when I  write the query from the example "or/and2/buy-profit/5g/buy-pct/60/and3/bid-profit/5g/bid-pct/60/left/30m". 
Sometimes I got it when I hover over items in my inventory too.

![wowscrnshot_122116_083559](https://cloud.githubusercontent.com/assets/8794030/21380942/c6c87c00-c758-11e6-8381-1e24ac0871f2.jpg)

**Comment by shirsig** [comment]
Hey. I think the problem is that you have an incompatible history format missing the time (at least in some entries). The query doesn't matter except that the more pages you scan the more likely you are to hit an item with a bad history. The easiest solution is to delete the account wide savedvariables file for aux.

**Comment by FlorianKromer** [comment]
It's fixed!
As you said, I deleted the lua in the savedvariables directory for my both accounts (old nostalrius and elysium)
