### ISSUE TITLE
[Request] Auto-Bid

### ISSUE THREAD

**Issue by BraynStorm** [shirsig/aux-addon#52]
Same as auto-buy but for bidding.

**Comment by shirsig** [comment]
I'm not convinced that this is useful enough. Would also need additional configuration like time left and probably a max count or something, which I'm not sure how to make a nice interface for. Why would you need this?

**Comment by jclock** [comment]
I can see it being used to make sure you can bid on items with no buyouts (not sure if auto buy does that right now), and making sure you are the highest bidder up to a certain amount or percentage of the item's value.

**Comment by shirsig** [comment]
I never really intended auto buy for this. I don't think you can ever get around manually inspecting the results of profit filters without making a loss overall. There are just too many false positives. The point of auto buy really is to be used together with real time mode for sniping specific items with manually adjusted price filters or to pick them up during a full scan.

The problem with auto bid is that most of the time it doesn't make much sense to bid on super good deals unless they're about to expire because you'll be outbid anyway, and until you are you have to wait to get your gold back and can't use it for something else. Plus you inflate the price by bidding early, so if you find a good bid deal you should probably not only not auto bid but not bid at all and instead wait until shortly before it expires. Even a time left filter wouldn't really solve this because the granularity is too big and it can't tell apart auctions expiring in 10 seconds from those expiring in 30 minutes. You can only know that by manually keeping track of an auction and observing when the time label changes.

**Comment by BraynStorm** [comment]
The reason I think it will be useful is that you can set it up (for example) to automatically bid on anything that has 30m left, and has bid < vendor price or something like that, and it will while you are searching for other stuff or just scanning the AH in the morning. The point is - yes it's not very useful for RealTime but in other cases there is merit, for example, you can link it with bid-profit or bid-percent. 

Cheers

**Comment by theoden-dd** [comment]
I agree with @BraynStorm. Auto-bidding every auction that has 30m left with a bid-vendor-profit set is a real world case.

**Comment by Sk1nk** [comment]
Would second that, even though I wouldn't limit it as suggested by @BraynStorm or @theoden-dd ... there are other things in the auctionhouse, no one even cares to bid for (gray items for example) so i would like to configure the filter myself like i used to and just have the "auto-bid" available next to the "auto-buy" ... the time left and bid vendor profit is easily set up with the current filter builder, no need to restrict auto-bid that way.

**Comment by theoden-dd** [comment]
Actually, we didn't suggest to restrict auto-bid in any manner. Instead we stated "it will be useful **at least** with these filter configurations".

Personally I'd prefer 
> just have the "auto-bid" available next to the "auto-buy"

, too, preserving the freedom of filter constructing.

**Comment by Sk1nk** [comment]
My fault then. I could think of more uses:
lets say you are scanning the auction house one last time at 2:00 am. Rather than buying thinks that where placed cheap in the auction house before players logged off, I would like to bid on them because the chance to get outbid is significantly lower at night, especially if we are talking about Sunday - Thursday night. That way you could raise the profit even more. Same goes for the time before a patch is applied. 

Or lets say i am comfortable with buying Silk Cloth for 2s per item. I don't care if Aux buys it if it is cheaper than 2s per Silk Cloth or if I get it after I won the bid race. I would love to let Aux look through the materials I need for leveling and buy those that I am comfortable to buy and bid on those, that match this criteria aswell, even though the buyout price is to high. Who cares if you get sniped later on that bid, as long as it increases the flow of Silk Cloth to my mailbox it would be a QoL improvement.

**Comment by psalkin** [comment]
That feature would complete AUX

**Comment by Altoholic** [comment]
Just now, someone outbided me on non buyable stuff in a way no human can do that fast (around 20 bids in a single second).
So, auto biding is already thing.

**Comment by shirsig** [comment]
Not relevant for classic.
