### ISSUE TITLE
Tooltips in aux

### ISSUE THREAD

**Issue by Larsy93** [shirsig/aux-addon#70]
Could we get it to show the full tooltip when hovering over items in Aux?

addons that attach to the "item frame" when hovering over them in the bag for example.

CompareStats is an addon that works in bag tooltips & item links but not in the aux window.

**Comment by shirsig** [comment]
that's never going to work. aux cannot use the auction item tooltip setter because that only works for the currently active auction page. The two alternatives are to scan the tooltip while on the page and recreate it later or to use the setter for an item id instead. Unless the addon also works for the item id setter neither of those methods can add the extra frame.
