### ISSUE TITLE
Non-hidden item is not in post list

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#87]
Can't find the [Rough Bronze Shoulders] in the post list while it's not hidden.
Unfortunately, it's the only reproducer I've found.
Full story in pics:
![wowscrnshot_021517_204441](https://cloud.githubusercontent.com/assets/2167281/23091134/38ab1496-f5c0-11e6-8b88-5fe0c03740c4.png)
![wowscrnshot_021517_204450](https://cloud.githubusercontent.com/assets/2167281/23091194/4dd28eac-f5c1-11e6-8234-2563a04af7ce.png)

**Comment by shirsig** [comment]
because you can't post items that don't have full durability

**Comment by theoden-dd** [comment]
Yes, you're right. I've got two more reproducers and signs are the same.

However, with containers it goes in a more user friendly way.
When I tried to sell [Heavy Bronze Lockbox]
there was a descriptive error "You cannot auction lootable item".
After that the item was marked as hidden.

How much effort will it take to make this durability error more obvious in the same manner?
It could keep you from reappearing of issues similar to this one.

**Comment by shirsig** [comment]
Actually, that wouldn't be more user friendly. What happens with the lockbox is that it's permanently hidden (same as checking the checkbox). The armor on the other hand will reappear when you've repaired it. I think simply ignoring the ones with reduced durability when parsing the inventory may be the best solution because it's possible to have more of the same item with full durability and then those should be auctionable without issues.

**Comment by theoden-dd** [comment]
You're right again. The difference is that lockbox is unpostable forever while broken items - temporarily.

What if show in post list the full quantity, and after pressing "post" button post all non-broken items and show error message if there were broken?
Something like "You cannot auction items with partial durability"

**Comment by revar** [comment]
You can post damaged item on BlizzardUI but it's not possible with Aux. Wtf?

**Comment by shirsig** [comment]
No, you can't.
